/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDexRouterRegistry,
  IDexRouterRegistryInterface,
} from "../../interfaces/IDexRouterRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
    ],
    name: "getRouterConfig",
    outputs: [
      {
        components: [
          {
            internalType: "enum IDexRouterRegistry.RouterType",
            name: "routerType",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "router",
            type: "address",
          },
          {
            internalType: "address",
            name: "positionManager",
            type: "address",
          },
          {
            internalType: "address",
            name: "wrappedNative",
            type: "address",
          },
          {
            internalType: "uint24",
            name: "fee",
            type: "uint24",
          },
          {
            internalType: "bool",
            name: "enabled",
            type: "bool",
          },
        ],
        internalType: "struct IDexRouterRegistry.RouterConfig",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
    ],
    name: "isChainSupported",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDexRouterRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDexRouterRegistryInterface {
    return new Interface(_abi) as IDexRouterRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDexRouterRegistry {
    return new Contract(address, _abi, runner) as unknown as IDexRouterRegistry;
  }
}
