import { ethers } from 'ethers';
import { getChainById, getDefaultChain } from '@/config/chains';
import { contractAddresses } from '@/config/contracts';
// Note: We import types that will be generated by TypeChain
// If this import fails in your IDE, run 'npm run typechain' or 'npx hardhat typechain'
import { 
  TokenFactory__factory, 
  BondingCurveAMM__factory,
  TokenFactory,
  BondingCurveAMM
} from '../../typechain-types';

export class BlockchainService {
  /**
   * Get a JSON RPC Provider for a specific chain
   */
  static getProvider(chainId: number): ethers.JsonRpcProvider {
    const chain = getChainById(chainId);
    if (!chain) {
      throw new Error(`Chain ID ${chainId} is not supported`);
    }

    const rpcUrl = chain.rpcUrls.default.http[0];
    return new ethers.JsonRpcProvider(rpcUrl);
  }

  /**
   * Get the TokenFactory contract instance (Strongly Typed)
   */
  static getTokenFactory(chainId: number, signer?: ethers.Signer): TokenFactory {
    const address = contractAddresses[chainId]?.TokenFactory;
    
    if (!address || address.trim() === '') {
      throw new Error(`TokenFactory not deployed on chain ${chainId}`);
    }

    const provider = this.getProvider(chainId);
    // Connect with signer if provided, otherwise read-only provider
    return TokenFactory__factory.connect(address, signer || provider);
  }

  /**
   * Get a BondingCurveAMM contract instance (Strongly Typed)
   */
  static getAMM(address: string, chainId: number, signer?: ethers.Signer): BondingCurveAMM {
    if (!ethers.isAddress(address)) {
      throw new Error(`Invalid AMM address: ${address}`);
    }

    const provider = this.getProvider(chainId);
    return BondingCurveAMM__factory.connect(address, signer || provider);
  }

  /**
   * Helper to resolve chain ID from optional param or default
   */
  static resolveChainId(chainIdParam?: string | number | null): number {
    if (!chainIdParam) return getDefaultChain().id;
    
    const parsed = Number(chainIdParam);
    return Number.isFinite(parsed) ? parsed : getDefaultChain().id;
  }
}
