/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KRC20Token__factory } from "./KRC20Token__factory";
export { TokenFactory__factory } from "./TokenFactory__factory";
