/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  BondingCurveMath,
  BondingCurveMathInterface,
} from "../../libraries/BondingCurveMath";

const _abi = [
  {
    inputs: [],
    name: "InvalidParameters",
    type: "error",
  },
  {
    inputs: [],
    name: "PriceTooLow",
    type: "error",
  },
  {
    inputs: [],
    name: "SupplyTooHigh",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e1e4d229fc951515f54525b06d707fc8474c7704ce95ef01f218e074d8423e3564736f6c63430008140033";

type BondingCurveMathConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BondingCurveMathConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BondingCurveMath__factory extends ContractFactory {
  constructor(...args: BondingCurveMathConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BondingCurveMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BondingCurveMath__factory {
    return super.connect(runner) as BondingCurveMath__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BondingCurveMathInterface {
    return new Interface(_abi) as BondingCurveMathInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BondingCurveMath {
    return new Contract(address, _abi, runner) as unknown as BondingCurveMath;
  }
}
