/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TokenFactory {
  export type TokenConfigStruct = {
    name: string;
    symbol: string;
    description: string;
    imageUrl: string;
    totalSupply: BigNumberish;
    basePrice: BigNumberish;
    slope: BigNumberish;
    curveType: BigNumberish;
    graduationThreshold: BigNumberish;
    creator: AddressLike;
    createdAt: BigNumberish;
  };

  export type TokenConfigStructOutput = [
    name: string,
    symbol: string,
    description: string,
    imageUrl: string,
    totalSupply: bigint,
    basePrice: bigint,
    slope: bigint,
    curveType: bigint,
    graduationThreshold: bigint,
    creator: string,
    createdAt: bigint
  ] & {
    name: string;
    symbol: string;
    description: string;
    imageUrl: string;
    totalSupply: bigint;
    basePrice: bigint;
    slope: bigint;
    curveType: bigint;
    graduationThreshold: bigint;
    creator: string;
    createdAt: bigint;
  };
}

export interface TokenFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATION_COOLDOWN"
      | "CREATION_FEE"
      | "MAX_DESCRIPTION_LENGTH"
      | "MAX_NAME_LENGTH"
      | "MAX_SYMBOL_LENGTH"
      | "MAX_TOTAL_SUPPLY"
      | "MIN_TOTAL_SUPPLY"
      | "PLATFORM_FEE"
      | "allTokens"
      | "createToken"
      | "dexRouterRegistry"
      | "feeRecipient"
      | "getAllTokens"
      | "getTokenAMM"
      | "getTokenConfig"
      | "getTotalTokens"
      | "isKasPumpToken"
      | "isValidToken"
      | "lastTokenCreation"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "tokenConfigs"
      | "tokenToAMM"
      | "transferOwnership"
      | "unpause"
      | "updateDexRouterRegistry"
      | "updateFeeRecipient"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreationFeeCollected"
      | "DexRouterRegistryUpdated"
      | "FeeRecipientUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "TokenCreated"
      | "TokenGraduated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATION_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATION_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DESCRIPTION_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_NAME_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SYMBOL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TOTAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_TOTAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dexRouterRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAMM",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isKasPumpToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastTokenCreation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToAMM",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateDexRouterRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeRecipient",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CREATION_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATION_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DESCRIPTION_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_NAME_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SYMBOL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TOTAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_TOTAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dexRouterRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAMM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKasPumpToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTokenCreation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenToAMM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDexRouterRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeRecipient",
    data: BytesLike
  ): Result;
}

export namespace CreationFeeCollectedEvent {
  export type InputTuple = [
    creator: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DexRouterRegistryUpdatedEvent {
  export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
  export type OutputTuple = [oldRegistry: string, newRegistry: string];
  export interface OutputObject {
    oldRegistry: string;
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [
    oldRecipient: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [oldRecipient: string, newRecipient: string];
  export interface OutputObject {
    oldRecipient: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    ammAddress: AddressLike,
    creator: AddressLike,
    name: string,
    symbol: string,
    totalSupply: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    ammAddress: string,
    creator: string,
    name: string,
    symbol: string,
    totalSupply: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    ammAddress: string;
    creator: string;
    name: string;
    symbol: string;
    totalSupply: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenGraduatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    finalSupply: BigNumberish,
    liquidityAdded: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    finalSupply: bigint,
    liquidityAdded: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    finalSupply: bigint;
    liquidityAdded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TokenFactory;
  waitForDeployment(): Promise<this>;

  interface: TokenFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATION_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  CREATION_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_DESCRIPTION_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_NAME_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_SYMBOL_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_TOTAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  MIN_TOTAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  allTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createToken: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _description: string,
      _imageUrl: string,
      _totalSupply: BigNumberish,
      _basePrice: BigNumberish,
      _slope: BigNumberish,
      _curveType: BigNumberish
    ],
    [[string, string] & { tokenAddress: string; ammAddress: string }],
    "payable"
  >;

  dexRouterRegistry: TypedContractMethod<[], [string], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getAllTokens: TypedContractMethod<[], [string[]], "view">;

  getTokenAMM: TypedContractMethod<
    [_tokenAddress: AddressLike],
    [string],
    "view"
  >;

  getTokenConfig: TypedContractMethod<
    [_tokenAddress: AddressLike],
    [TokenFactory.TokenConfigStructOutput],
    "view"
  >;

  getTotalTokens: TypedContractMethod<[], [bigint], "view">;

  isKasPumpToken: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isValidToken: TypedContractMethod<[_token: AddressLike], [boolean], "view">;

  lastTokenCreation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  tokenConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        name: string;
        symbol: string;
        description: string;
        imageUrl: string;
        totalSupply: bigint;
        basePrice: bigint;
        slope: bigint;
        curveType: bigint;
        graduationThreshold: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  tokenToAMM: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateDexRouterRegistry: TypedContractMethod<
    [_newRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFeeRecipient: TypedContractMethod<
    [_newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATION_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATION_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DESCRIPTION_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_NAME_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SYMBOL_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TOTAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TOTAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _description: string,
      _imageUrl: string,
      _totalSupply: BigNumberish,
      _basePrice: BigNumberish,
      _slope: BigNumberish,
      _curveType: BigNumberish
    ],
    [[string, string] & { tokenAddress: string; ammAddress: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dexRouterRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTokenAMM"
  ): TypedContractMethod<[_tokenAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenConfig"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike],
    [TokenFactory.TokenConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isKasPumpToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidToken"
  ): TypedContractMethod<[_token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastTokenCreation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        name: string;
        symbol: string;
        description: string;
        imageUrl: string;
        totalSupply: bigint;
        basePrice: bigint;
        slope: bigint;
        curveType: bigint;
        graduationThreshold: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenToAMM"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDexRouterRegistry"
  ): TypedContractMethod<[_newRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFeeRecipient"
  ): TypedContractMethod<[_newRecipient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CreationFeeCollected"
  ): TypedContractEvent<
    CreationFeeCollectedEvent.InputTuple,
    CreationFeeCollectedEvent.OutputTuple,
    CreationFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "DexRouterRegistryUpdated"
  ): TypedContractEvent<
    DexRouterRegistryUpdatedEvent.InputTuple,
    DexRouterRegistryUpdatedEvent.OutputTuple,
    DexRouterRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenGraduated"
  ): TypedContractEvent<
    TokenGraduatedEvent.InputTuple,
    TokenGraduatedEvent.OutputTuple,
    TokenGraduatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CreationFeeCollected(address,uint256,uint256)": TypedContractEvent<
      CreationFeeCollectedEvent.InputTuple,
      CreationFeeCollectedEvent.OutputTuple,
      CreationFeeCollectedEvent.OutputObject
    >;
    CreationFeeCollected: TypedContractEvent<
      CreationFeeCollectedEvent.InputTuple,
      CreationFeeCollectedEvent.OutputTuple,
      CreationFeeCollectedEvent.OutputObject
    >;

    "DexRouterRegistryUpdated(address,address)": TypedContractEvent<
      DexRouterRegistryUpdatedEvent.InputTuple,
      DexRouterRegistryUpdatedEvent.OutputTuple,
      DexRouterRegistryUpdatedEvent.OutputObject
    >;
    DexRouterRegistryUpdated: TypedContractEvent<
      DexRouterRegistryUpdatedEvent.InputTuple,
      DexRouterRegistryUpdatedEvent.OutputTuple,
      DexRouterRegistryUpdatedEvent.OutputObject
    >;

    "FeeRecipientUpdated(address,address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TokenCreated(address,address,address,string,string,uint256,uint256)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;

    "TokenGraduated(address,uint256,uint256)": TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;
    TokenGraduated: TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
