/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DeterministicDeployerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "computeTokenFactoryAddress"
      | "deployTokenFactory"
      | "deployTokenFactoryWithRegistry"
      | "deployedContracts"
      | "deploymentNonce"
      | "getDeployment"
      | "isDeployed"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "transferTokenFactoryOwnership"
      | "updateTokenFactoryRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractDeployed"
      | "OwnershipTransferred"
      | "TokenFactoryOwnershipTransferred"
      | "TokenFactoryRegistryConfigured"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "computeTokenFactoryAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployTokenFactory",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployTokenFactoryWithRegistry",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedContracts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeployed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokenFactoryOwnership",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenFactoryRegistry",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeTokenFactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployTokenFactoryWithRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDeployed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokenFactoryOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenFactoryRegistry",
    data: BytesLike
  ): Result;
}

export namespace ContractDeployedEvent {
  export type InputTuple = [
    contractAddress: AddressLike,
    salt: BytesLike,
    contractType: string,
    chainId: BigNumberish
  ];
  export type OutputTuple = [
    contractAddress: string,
    salt: string,
    contractType: string,
    chainId: bigint
  ];
  export interface OutputObject {
    contractAddress: string;
    salt: string;
    contractType: string;
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFactoryOwnershipTransferredEvent {
  export type InputTuple = [factoryAddress: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [factoryAddress: string, newOwner: string];
  export interface OutputObject {
    factoryAddress: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFactoryRegistryConfiguredEvent {
  export type InputTuple = [
    factoryAddress: AddressLike,
    registryAddress: AddressLike
  ];
  export type OutputTuple = [factoryAddress: string, registryAddress: string];
  export interface OutputObject {
    factoryAddress: string;
    registryAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeterministicDeployer extends BaseContract {
  connect(runner?: ContractRunner | null): DeterministicDeployer;
  waitForDeployment(): Promise<this>;

  interface: DeterministicDeployerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeTokenFactoryAddress: TypedContractMethod<
    [_baseSalt: BytesLike, _feeRecipient: AddressLike],
    [string],
    "view"
  >;

  deployTokenFactory: TypedContractMethod<
    [_feeRecipient: AddressLike, _baseSalt: BytesLike],
    [string],
    "nonpayable"
  >;

  deployTokenFactoryWithRegistry: TypedContractMethod<
    [
      _feeRecipient: AddressLike,
      _baseSalt: BytesLike,
      _dexRouterRegistry: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  deployedContracts: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  deploymentNonce: TypedContractMethod<[], [bigint], "view">;

  getDeployment: TypedContractMethod<[salt: BytesLike], [string], "view">;

  isDeployed: TypedContractMethod<[salt: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferTokenFactoryOwnership: TypedContractMethod<
    [_baseSalt: BytesLike, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTokenFactoryRegistry: TypedContractMethod<
    [_baseSalt: BytesLike, _dexRouterRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeTokenFactoryAddress"
  ): TypedContractMethod<
    [_baseSalt: BytesLike, _feeRecipient: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployTokenFactory"
  ): TypedContractMethod<
    [_feeRecipient: AddressLike, _baseSalt: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployTokenFactoryWithRegistry"
  ): TypedContractMethod<
    [
      _feeRecipient: AddressLike,
      _baseSalt: BytesLike,
      _dexRouterRegistry: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedContracts"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "deploymentNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDeployment"
  ): TypedContractMethod<[salt: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isDeployed"
  ): TypedContractMethod<[salt: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferTokenFactoryOwnership"
  ): TypedContractMethod<
    [_baseSalt: BytesLike, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTokenFactoryRegistry"
  ): TypedContractMethod<
    [_baseSalt: BytesLike, _dexRouterRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContractDeployed"
  ): TypedContractEvent<
    ContractDeployedEvent.InputTuple,
    ContractDeployedEvent.OutputTuple,
    ContractDeployedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenFactoryOwnershipTransferred"
  ): TypedContractEvent<
    TokenFactoryOwnershipTransferredEvent.InputTuple,
    TokenFactoryOwnershipTransferredEvent.OutputTuple,
    TokenFactoryOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenFactoryRegistryConfigured"
  ): TypedContractEvent<
    TokenFactoryRegistryConfiguredEvent.InputTuple,
    TokenFactoryRegistryConfiguredEvent.OutputTuple,
    TokenFactoryRegistryConfiguredEvent.OutputObject
  >;

  filters: {
    "ContractDeployed(address,bytes32,string,uint256)": TypedContractEvent<
      ContractDeployedEvent.InputTuple,
      ContractDeployedEvent.OutputTuple,
      ContractDeployedEvent.OutputObject
    >;
    ContractDeployed: TypedContractEvent<
      ContractDeployedEvent.InputTuple,
      ContractDeployedEvent.OutputTuple,
      ContractDeployedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenFactoryOwnershipTransferred(address,address)": TypedContractEvent<
      TokenFactoryOwnershipTransferredEvent.InputTuple,
      TokenFactoryOwnershipTransferredEvent.OutputTuple,
      TokenFactoryOwnershipTransferredEvent.OutputObject
    >;
    TokenFactoryOwnershipTransferred: TypedContractEvent<
      TokenFactoryOwnershipTransferredEvent.InputTuple,
      TokenFactoryOwnershipTransferredEvent.OutputTuple,
      TokenFactoryOwnershipTransferredEvent.OutputObject
    >;

    "TokenFactoryRegistryConfigured(address,address)": TypedContractEvent<
      TokenFactoryRegistryConfiguredEvent.InputTuple,
      TokenFactoryRegistryConfiguredEvent.OutputTuple,
      TokenFactoryRegistryConfiguredEvent.OutputObject
    >;
    TokenFactoryRegistryConfigured: TypedContractEvent<
      TokenFactoryRegistryConfiguredEvent.InputTuple,
      TokenFactoryRegistryConfiguredEvent.OutputTuple,
      TokenFactoryRegistryConfiguredEvent.OutputObject
    >;
  };
}
