/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MultiChainDeploymentHelper {
  export type ChainDeploymentStruct = {
    chainId: BigNumberish;
    tokenFactoryAddress: AddressLike;
    deployerAddress: AddressLike;
    deployedAt: BigNumberish;
    isActive: boolean;
  };

  export type ChainDeploymentStructOutput = [
    chainId: bigint,
    tokenFactoryAddress: string,
    deployerAddress: string,
    deployedAt: bigint,
    isActive: boolean
  ] & {
    chainId: bigint;
    tokenFactoryAddress: string;
    deployerAddress: string;
    deployedAt: bigint;
    isActive: boolean;
  };
}

export interface MultiChainDeploymentHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "chainDeployments"
      | "getChainDeployment"
      | "getSupportedChains"
      | "owner"
      | "registerDeployment"
      | "renounceOwnership"
      | "supportedChainIds"
      | "transferOwnership"
      | "verifyConsistentAddresses"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ChainDeploymentRegistered" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "chainDeployments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainDeployment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedChains",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDeployment",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedChainIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyConsistentAddresses",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "chainDeployments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedChainIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyConsistentAddresses",
    data: BytesLike
  ): Result;
}

export namespace ChainDeploymentRegisteredEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    factoryAddress: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    chainId: bigint,
    factoryAddress: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    chainId: bigint;
    factoryAddress: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiChainDeploymentHelper extends BaseContract {
  connect(runner?: ContractRunner | null): MultiChainDeploymentHelper;
  waitForDeployment(): Promise<this>;

  interface: MultiChainDeploymentHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  chainDeployments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        chainId: bigint;
        tokenFactoryAddress: string;
        deployerAddress: string;
        deployedAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getChainDeployment: TypedContractMethod<
    [_chainId: BigNumberish],
    [MultiChainDeploymentHelper.ChainDeploymentStructOutput],
    "view"
  >;

  getSupportedChains: TypedContractMethod<[], [bigint[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerDeployment: TypedContractMethod<
    [
      _chainId: BigNumberish,
      _factoryAddress: AddressLike,
      _deployerAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supportedChainIds: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyConsistentAddresses: TypedContractMethod<
    [],
    [[boolean, string] & { isConsistent: boolean; expectedAddress: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "chainDeployments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        chainId: bigint;
        tokenFactoryAddress: string;
        deployerAddress: string;
        deployedAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChainDeployment"
  ): TypedContractMethod<
    [_chainId: BigNumberish],
    [MultiChainDeploymentHelper.ChainDeploymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedChains"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDeployment"
  ): TypedContractMethod<
    [
      _chainId: BigNumberish,
      _factoryAddress: AddressLike,
      _deployerAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedChainIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyConsistentAddresses"
  ): TypedContractMethod<
    [],
    [[boolean, string] & { isConsistent: boolean; expectedAddress: string }],
    "view"
  >;

  getEvent(
    key: "ChainDeploymentRegistered"
  ): TypedContractEvent<
    ChainDeploymentRegisteredEvent.InputTuple,
    ChainDeploymentRegisteredEvent.OutputTuple,
    ChainDeploymentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ChainDeploymentRegistered(uint256,address,uint256)": TypedContractEvent<
      ChainDeploymentRegisteredEvent.InputTuple,
      ChainDeploymentRegisteredEvent.OutputTuple,
      ChainDeploymentRegisteredEvent.OutputObject
    >;
    ChainDeploymentRegistered: TypedContractEvent<
      ChainDeploymentRegisteredEvent.InputTuple,
      ChainDeploymentRegisteredEvent.OutputTuple,
      ChainDeploymentRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
