/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IDexRouterRegistry {
  export type RouterConfigStruct = {
    routerType: BigNumberish;
    router: AddressLike;
    positionManager: AddressLike;
    wrappedNative: AddressLike;
    fee: BigNumberish;
    enabled: boolean;
  };

  export type RouterConfigStructOutput = [
    routerType: bigint,
    router: string,
    positionManager: string,
    wrappedNative: string,
    fee: bigint,
    enabled: boolean
  ] & {
    routerType: bigint;
    router: string;
    positionManager: string;
    wrappedNative: string;
    fee: bigint;
    enabled: boolean;
  };
}

export interface IDexRouterRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getRouterConfig" | "isChainSupported"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRouterConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isChainSupported",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRouterConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isChainSupported",
    data: BytesLike
  ): Result;
}

export interface IDexRouterRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IDexRouterRegistry;
  waitForDeployment(): Promise<this>;

  interface: IDexRouterRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRouterConfig: TypedContractMethod<
    [chainId: BigNumberish],
    [IDexRouterRegistry.RouterConfigStructOutput],
    "view"
  >;

  isChainSupported: TypedContractMethod<
    [chainId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRouterConfig"
  ): TypedContractMethod<
    [chainId: BigNumberish],
    [IDexRouterRegistry.RouterConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isChainSupported"
  ): TypedContractMethod<[chainId: BigNumberish], [boolean], "view">;

  filters: {};
}
