/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BondingCurveAMMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIC_FEE"
      | "CREATOR_PERCENT"
      | "DEX_LIQUIDITY_PERCENT"
      | "DEX_SLIPPAGE_TOLERANCE"
      | "ENTERPRISE_FEE"
      | "LP_LOCK_DURATION"
      | "MAX_BASE_PRICE"
      | "MAX_SLIPPAGE"
      | "MAX_SLOPE"
      | "MAX_TOTAL_SUPPLY"
      | "MIN_BASE_PRICE"
      | "PLATFORM_PERCENT"
      | "PRECISION"
      | "PREMIUM_FEE"
      | "basePrice"
      | "buyTokens"
      | "calculateNativeOut"
      | "calculateTokensOut"
      | "currentSupply"
      | "curveType"
      | "dexRouter"
      | "emergencyWithdraw"
      | "feeRecipient"
      | "getCurrentPrice"
      | "getPlatformFee"
      | "getPriceImpact"
      | "getTradingInfo"
      | "graduationThreshold"
      | "isGraduated"
      | "lpTokenAddress"
      | "lpTokensLocked"
      | "lpUnlockTime"
      | "membershipTier"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "sellTokens"
      | "slope"
      | "token"
      | "tokenCreator"
      | "totalGraduationFunds"
      | "totalVolume"
      | "transferOwnership"
      | "unpause"
      | "withdrawGraduationFunds"
      | "withdrawLPTokens"
      | "withdrawableGraduationFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdraw"
      | "Graduated"
      | "GraduationFundsSplit"
      | "GraduationFundsWithdrawn"
      | "LPTokensLocked"
      | "LPTokensWithdrawn"
      | "LiquidityAdded"
      | "OwnershipTransferred"
      | "Paused"
      | "Trade"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BASIC_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CREATOR_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEX_LIQUIDITY_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEX_SLIPPAGE_TOLERANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ENTERPRISE_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LP_LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SLIPPAGE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_SLOPE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_TOTAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PREMIUM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "basePrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNativeOut",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTokensOut",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "curveType", values?: undefined): string;
  encodeFunctionData(functionFragment: "dexRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceImpact",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradingInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "graduationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isGraduated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpTokensLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpUnlockTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "membershipTier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "slope", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenCreator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalGraduationFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawGraduationFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLPTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawableGraduationFunds",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "BASIC_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEX_LIQUIDITY_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEX_SLIPPAGE_TOLERANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ENTERPRISE_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LP_LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BASE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SLIPPAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SLOPE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TOTAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BASE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PREMIUM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "basePrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateNativeOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTokensOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "curveType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dexRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceImpact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "graduationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGraduated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpTokensLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "membershipTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slope", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGraduationFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawGraduationFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLPTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawableGraduationFunds",
    data: BytesLike
  ): Result;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    admin: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [admin: string, amount: bigint, reason: string];
  export interface OutputObject {
    admin: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GraduatedEvent {
  export type InputTuple = [
    finalSupply: BigNumberish,
    nativeReserve: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    finalSupply: bigint,
    nativeReserve: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    finalSupply: bigint;
    nativeReserve: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GraduationFundsSplitEvent {
  export type InputTuple = [
    creatorShare: BigNumberish,
    platformShare: BigNumberish,
    creator: AddressLike,
    platform: AddressLike
  ];
  export type OutputTuple = [
    creatorShare: bigint,
    platformShare: bigint,
    creator: string,
    platform: string
  ];
  export interface OutputObject {
    creatorShare: bigint;
    platformShare: bigint;
    creator: string;
    platform: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GraduationFundsWithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPTokensLockedEvent {
  export type InputTuple = [
    amount: BigNumberish,
    unlockTime: BigNumberish,
    lpToken: AddressLike
  ];
  export type OutputTuple = [
    amount: bigint,
    unlockTime: bigint,
    lpToken: string
  ];
  export interface OutputObject {
    amount: bigint;
    unlockTime: bigint;
    lpToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPTokensWithdrawnEvent {
  export type InputTuple = [
    creator: AddressLike,
    amount: BigNumberish,
    lpToken: AddressLike
  ];
  export type OutputTuple = [creator: string, amount: bigint, lpToken: string];
  export interface OutputObject {
    creator: string;
    amount: bigint;
    lpToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    tokenAmount: BigNumberish,
    nativeAmount: BigNumberish,
    liquidity: BigNumberish,
    lpTokenAddress: AddressLike,
    dexPair: AddressLike
  ];
  export type OutputTuple = [
    tokenAmount: bigint,
    nativeAmount: bigint,
    liquidity: bigint,
    lpTokenAddress: string,
    dexPair: string
  ];
  export interface OutputObject {
    tokenAmount: bigint;
    nativeAmount: bigint;
    liquidity: bigint;
    lpTokenAddress: string;
    dexPair: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    trader: AddressLike,
    isBuy: boolean,
    nativeAmount: BigNumberish,
    tokenAmount: BigNumberish,
    newPrice: BigNumberish,
    fee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    isBuy: boolean,
    nativeAmount: bigint,
    tokenAmount: bigint,
    newPrice: bigint,
    fee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    trader: string;
    isBuy: boolean;
    nativeAmount: bigint;
    tokenAmount: bigint;
    newPrice: bigint;
    fee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BondingCurveAMM extends BaseContract {
  connect(runner?: ContractRunner | null): BondingCurveAMM;
  waitForDeployment(): Promise<this>;

  interface: BondingCurveAMMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIC_FEE: TypedContractMethod<[], [bigint], "view">;

  CREATOR_PERCENT: TypedContractMethod<[], [bigint], "view">;

  DEX_LIQUIDITY_PERCENT: TypedContractMethod<[], [bigint], "view">;

  DEX_SLIPPAGE_TOLERANCE: TypedContractMethod<[], [bigint], "view">;

  ENTERPRISE_FEE: TypedContractMethod<[], [bigint], "view">;

  LP_LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  MAX_SLIPPAGE: TypedContractMethod<[], [bigint], "view">;

  MAX_SLOPE: TypedContractMethod<[], [bigint], "view">;

  MAX_TOTAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  MIN_BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_PERCENT: TypedContractMethod<[], [bigint], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  PREMIUM_FEE: TypedContractMethod<[], [bigint], "view">;

  basePrice: TypedContractMethod<[], [bigint], "view">;

  buyTokens: TypedContractMethod<
    [minTokensOut: BigNumberish],
    [void],
    "payable"
  >;

  calculateNativeOut: TypedContractMethod<
    [tokensIn: BigNumberish, supply: BigNumberish],
    [bigint],
    "view"
  >;

  calculateTokensOut: TypedContractMethod<
    [nativeIn: BigNumberish, supply: BigNumberish],
    [bigint],
    "view"
  >;

  currentSupply: TypedContractMethod<[], [bigint], "view">;

  curveType: TypedContractMethod<[], [bigint], "view">;

  dexRouter: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<
    [reason: string],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getCurrentPrice: TypedContractMethod<[], [bigint], "view">;

  getPlatformFee: TypedContractMethod<[], [bigint], "view">;

  getPriceImpact: TypedContractMethod<
    [amount: BigNumberish, isBuy: boolean],
    [bigint],
    "view"
  >;

  getTradingInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        _currentSupply: bigint;
        _currentPrice: bigint;
        _totalVolume: bigint;
        _graduationProgress: bigint;
        _isGraduated: boolean;
      }
    ],
    "view"
  >;

  graduationThreshold: TypedContractMethod<[], [bigint], "view">;

  isGraduated: TypedContractMethod<[], [boolean], "view">;

  lpTokenAddress: TypedContractMethod<[], [string], "view">;

  lpTokensLocked: TypedContractMethod<[], [bigint], "view">;

  lpUnlockTime: TypedContractMethod<[], [bigint], "view">;

  membershipTier: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellTokens: TypedContractMethod<
    [tokenAmount: BigNumberish, minNativeOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  slope: TypedContractMethod<[], [bigint], "view">;

  token: TypedContractMethod<[], [string], "view">;

  tokenCreator: TypedContractMethod<[], [string], "view">;

  totalGraduationFunds: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawGraduationFunds: TypedContractMethod<[], [void], "nonpayable">;

  withdrawLPTokens: TypedContractMethod<[], [void], "nonpayable">;

  withdrawableGraduationFunds: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIC_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATOR_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEX_LIQUIDITY_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEX_SLIPPAGE_TOLERANCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ENTERPRISE_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LP_LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SLIPPAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SLOPE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TOTAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PREMIUM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "basePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyTokens"
  ): TypedContractMethod<[minTokensOut: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "calculateNativeOut"
  ): TypedContractMethod<
    [tokensIn: BigNumberish, supply: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateTokensOut"
  ): TypedContractMethod<
    [nativeIn: BigNumberish, supply: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "curveType"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dexRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[reason: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlatformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPriceImpact"
  ): TypedContractMethod<
    [amount: BigNumberish, isBuy: boolean],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTradingInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        _currentSupply: bigint;
        _currentPrice: bigint;
        _totalVolume: bigint;
        _graduationProgress: bigint;
        _isGraduated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "graduationThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isGraduated"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lpTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lpTokensLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpUnlockTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "membershipTier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellTokens"
  ): TypedContractMethod<
    [tokenAmount: BigNumberish, minNativeOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slope"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenCreator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalGraduationFunds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawGraduationFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawLPTokens"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawableGraduationFunds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "Graduated"
  ): TypedContractEvent<
    GraduatedEvent.InputTuple,
    GraduatedEvent.OutputTuple,
    GraduatedEvent.OutputObject
  >;
  getEvent(
    key: "GraduationFundsSplit"
  ): TypedContractEvent<
    GraduationFundsSplitEvent.InputTuple,
    GraduationFundsSplitEvent.OutputTuple,
    GraduationFundsSplitEvent.OutputObject
  >;
  getEvent(
    key: "GraduationFundsWithdrawn"
  ): TypedContractEvent<
    GraduationFundsWithdrawnEvent.InputTuple,
    GraduationFundsWithdrawnEvent.OutputTuple,
    GraduationFundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "LPTokensLocked"
  ): TypedContractEvent<
    LPTokensLockedEvent.InputTuple,
    LPTokensLockedEvent.OutputTuple,
    LPTokensLockedEvent.OutputObject
  >;
  getEvent(
    key: "LPTokensWithdrawn"
  ): TypedContractEvent<
    LPTokensWithdrawnEvent.InputTuple,
    LPTokensWithdrawnEvent.OutputTuple,
    LPTokensWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdraw(address,uint256,string)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "Graduated(uint256,uint256,uint256)": TypedContractEvent<
      GraduatedEvent.InputTuple,
      GraduatedEvent.OutputTuple,
      GraduatedEvent.OutputObject
    >;
    Graduated: TypedContractEvent<
      GraduatedEvent.InputTuple,
      GraduatedEvent.OutputTuple,
      GraduatedEvent.OutputObject
    >;

    "GraduationFundsSplit(uint256,uint256,address,address)": TypedContractEvent<
      GraduationFundsSplitEvent.InputTuple,
      GraduationFundsSplitEvent.OutputTuple,
      GraduationFundsSplitEvent.OutputObject
    >;
    GraduationFundsSplit: TypedContractEvent<
      GraduationFundsSplitEvent.InputTuple,
      GraduationFundsSplitEvent.OutputTuple,
      GraduationFundsSplitEvent.OutputObject
    >;

    "GraduationFundsWithdrawn(address,uint256)": TypedContractEvent<
      GraduationFundsWithdrawnEvent.InputTuple,
      GraduationFundsWithdrawnEvent.OutputTuple,
      GraduationFundsWithdrawnEvent.OutputObject
    >;
    GraduationFundsWithdrawn: TypedContractEvent<
      GraduationFundsWithdrawnEvent.InputTuple,
      GraduationFundsWithdrawnEvent.OutputTuple,
      GraduationFundsWithdrawnEvent.OutputObject
    >;

    "LPTokensLocked(uint256,uint256,address)": TypedContractEvent<
      LPTokensLockedEvent.InputTuple,
      LPTokensLockedEvent.OutputTuple,
      LPTokensLockedEvent.OutputObject
    >;
    LPTokensLocked: TypedContractEvent<
      LPTokensLockedEvent.InputTuple,
      LPTokensLockedEvent.OutputTuple,
      LPTokensLockedEvent.OutputObject
    >;

    "LPTokensWithdrawn(address,uint256,address)": TypedContractEvent<
      LPTokensWithdrawnEvent.InputTuple,
      LPTokensWithdrawnEvent.OutputTuple,
      LPTokensWithdrawnEvent.OutputObject
    >;
    LPTokensWithdrawn: TypedContractEvent<
      LPTokensWithdrawnEvent.InputTuple,
      LPTokensWithdrawnEvent.OutputTuple,
      LPTokensWithdrawnEvent.OutputObject
    >;

    "LiquidityAdded(uint256,uint256,uint256,address,address)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Trade(address,bool,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
