/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IDexRouterRegistry {
  export type RouterConfigStruct = {
    routerType: BigNumberish;
    router: AddressLike;
    positionManager: AddressLike;
    wrappedNative: AddressLike;
    fee: BigNumberish;
    enabled: boolean;
  };

  export type RouterConfigStructOutput = [
    routerType: bigint,
    router: string,
    positionManager: string,
    wrappedNative: string,
    fee: bigint,
    enabled: boolean
  ] & {
    routerType: bigint;
    router: string;
    positionManager: string;
    wrappedNative: string;
    fee: bigint;
    enabled: boolean;
  };
}

export interface DexRouterRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRouterConfig"
      | "isChainSupported"
      | "owner"
      | "renounceOwnership"
      | "setRouterConfig"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "RouterConfigUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getRouterConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isChainSupported",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRouterConfig",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRouterConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isChainSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRouterConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterConfigUpdatedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    routerType: BigNumberish,
    router: AddressLike,
    positionManager: AddressLike,
    wrappedNative: AddressLike,
    fee: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    chainId: bigint,
    routerType: bigint,
    router: string,
    positionManager: string,
    wrappedNative: string,
    fee: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    chainId: bigint;
    routerType: bigint;
    router: string;
    positionManager: string;
    wrappedNative: string;
    fee: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DexRouterRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DexRouterRegistry;
  waitForDeployment(): Promise<this>;

  interface: DexRouterRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRouterConfig: TypedContractMethod<
    [chainId: BigNumberish],
    [IDexRouterRegistry.RouterConfigStructOutput],
    "view"
  >;

  isChainSupported: TypedContractMethod<
    [chainId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRouterConfig: TypedContractMethod<
    [
      chainId: BigNumberish,
      routerType: BigNumberish,
      router: AddressLike,
      positionManager: AddressLike,
      wrappedNative: AddressLike,
      fee: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRouterConfig"
  ): TypedContractMethod<
    [chainId: BigNumberish],
    [IDexRouterRegistry.RouterConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isChainSupported"
  ): TypedContractMethod<[chainId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRouterConfig"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      routerType: BigNumberish,
      router: AddressLike,
      positionManager: AddressLike,
      wrappedNative: AddressLike,
      fee: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RouterConfigUpdated"
  ): TypedContractEvent<
    RouterConfigUpdatedEvent.InputTuple,
    RouterConfigUpdatedEvent.OutputTuple,
    RouterConfigUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RouterConfigUpdated(uint256,uint8,address,address,address,uint24,bool)": TypedContractEvent<
      RouterConfigUpdatedEvent.InputTuple,
      RouterConfigUpdatedEvent.OutputTuple,
      RouterConfigUpdatedEvent.OutputObject
    >;
    RouterConfigUpdated: TypedContractEvent<
      RouterConfigUpdatedEvent.InputTuple,
      RouterConfigUpdatedEvent.OutputTuple,
      RouterConfigUpdatedEvent.OutputObject
    >;
  };
}
