/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LimitOrderBook {
  export type OrderStruct = {
    orderId: BigNumberish;
    trader: AddressLike;
    tokenAddress: AddressLike;
    isBuyOrder: boolean;
    price: BigNumberish;
    amount: BigNumberish;
    filled: BigNumberish;
    timestamp: BigNumberish;
    cancelled: boolean;
  };

  export type OrderStructOutput = [
    orderId: bigint,
    trader: string,
    tokenAddress: string,
    isBuyOrder: boolean,
    price: bigint,
    amount: bigint,
    filled: bigint,
    timestamp: bigint,
    cancelled: boolean
  ] & {
    orderId: bigint;
    trader: string;
    tokenAddress: string;
    isBuyOrder: boolean;
    price: bigint;
    amount: bigint;
    filled: bigint;
    timestamp: bigint;
    cancelled: boolean;
  };
}

export interface LimitOrderBookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "cancelOrder"
      | "createBuyOrder"
      | "createSellOrder"
      | "feeRecipient"
      | "fillBuyOrder"
      | "fillSellOrder"
      | "getOrder"
      | "getTokenBuyOrders"
      | "getTokenSellOrders"
      | "getTraderOrders"
      | "minOrderSize"
      | "minTokenOrderSize"
      | "nextOrderId"
      | "orders"
      | "owner"
      | "platformFee"
      | "renounceOwnership"
      | "setFeeRecipient"
      | "setMinOrderSize"
      | "setMinTokenOrderSize"
      | "setPlatformFee"
      | "tokenBuyOrders"
      | "tokenSellOrders"
      | "traderOrders"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderFilled"
      | "OrderPartiallyFilled"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBuyOrder",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellOrder",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fillBuyOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fillSellOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBuyOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenSellOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraderOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minOrderSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTokenOrderSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinOrderSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinTokenOrderSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBuyOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenSellOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "traderOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBuyOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenSellOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraderOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minOrderSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTokenOrderSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinOrderSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinTokenOrderSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBuyOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenSellOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "traderOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish, trader: AddressLike];
  export type OutputTuple = [orderId: bigint, trader: string];
  export interface OutputObject {
    orderId: bigint;
    trader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    trader: AddressLike,
    tokenAddress: AddressLike,
    isBuyOrder: boolean,
    price: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    trader: string,
    tokenAddress: string,
    isBuyOrder: boolean,
    price: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    trader: string;
    tokenAddress: string;
    isBuyOrder: boolean;
    price: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    filler: AddressLike,
    amount: BigNumberish,
    totalCost: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    filler: string,
    amount: bigint,
    totalCost: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    filler: string;
    amount: bigint;
    totalCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderPartiallyFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    filledAmount: BigNumberish,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    filledAmount: bigint,
    remainingAmount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    filledAmount: bigint;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LimitOrderBook extends BaseContract {
  connect(runner?: ContractRunner | null): LimitOrderBook;
  waitForDeployment(): Promise<this>;

  interface: LimitOrderBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBuyOrder: TypedContractMethod<
    [tokenAddress: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "payable"
  >;

  createSellOrder: TypedContractMethod<
    [tokenAddress: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  fillBuyOrder: TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fillSellOrder: TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [LimitOrderBook.OrderStructOutput],
    "view"
  >;

  getTokenBuyOrders: TypedContractMethod<
    [token: AddressLike],
    [bigint[]],
    "view"
  >;

  getTokenSellOrders: TypedContractMethod<
    [token: AddressLike],
    [bigint[]],
    "view"
  >;

  getTraderOrders: TypedContractMethod<
    [trader: AddressLike],
    [bigint[]],
    "view"
  >;

  minOrderSize: TypedContractMethod<[], [bigint], "view">;

  minTokenOrderSize: TypedContractMethod<[], [bigint], "view">;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        orderId: bigint;
        trader: string;
        tokenAddress: string;
        isBuyOrder: boolean;
        price: bigint;
        amount: bigint;
        filled: bigint;
        timestamp: bigint;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinOrderSize: TypedContractMethod<
    [newMinSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinTokenOrderSize: TypedContractMethod<
    [newMinSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenBuyOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  tokenSellOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  traderOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBuyOrder"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createSellOrder"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fillBuyOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fillSellOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [LimitOrderBook.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenBuyOrders"
  ): TypedContractMethod<[token: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTokenSellOrders"
  ): TypedContractMethod<[token: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTraderOrders"
  ): TypedContractMethod<[trader: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "minOrderSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minTokenOrderSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        orderId: bigint;
        trader: string;
        tokenAddress: string;
        isBuyOrder: boolean;
        price: bigint;
        amount: bigint;
        filled: bigint;
        timestamp: bigint;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinOrderSize"
  ): TypedContractMethod<[newMinSize: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinTokenOrderSize"
  ): TypedContractMethod<[newMinSize: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenBuyOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenSellOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "traderOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OrderPartiallyFilled"
  ): TypedContractEvent<
    OrderPartiallyFilledEvent.InputTuple,
    OrderPartiallyFilledEvent.OutputTuple,
    OrderPartiallyFilledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OrderCancelled(uint256,address)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address,bool,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderFilled(uint256,address,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OrderPartiallyFilled(uint256,uint256,uint256)": TypedContractEvent<
      OrderPartiallyFilledEvent.InputTuple,
      OrderPartiallyFilledEvent.OutputTuple,
      OrderPartiallyFilledEvent.OutputObject
    >;
    OrderPartiallyFilled: TypedContractEvent<
      OrderPartiallyFilledEvent.InputTuple,
      OrderPartiallyFilledEvent.OutputTuple,
      OrderPartiallyFilledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
