/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace StopLossOrderBook {
  export type StopLossOrderStruct = {
    orderId: BigNumberish;
    trader: AddressLike;
    tokenAddress: AddressLike;
    ammAddress: AddressLike;
    triggerPrice: BigNumberish;
    amount: BigNumberish;
    minReceive: BigNumberish;
    timestamp: BigNumberish;
    executed: boolean;
    cancelled: boolean;
  };

  export type StopLossOrderStructOutput = [
    orderId: bigint,
    trader: string,
    tokenAddress: string,
    ammAddress: string,
    triggerPrice: bigint,
    amount: bigint,
    minReceive: bigint,
    timestamp: bigint,
    executed: boolean,
    cancelled: boolean
  ] & {
    orderId: bigint;
    trader: string;
    tokenAddress: string;
    ammAddress: string;
    triggerPrice: bigint;
    amount: bigint;
    minReceive: bigint;
    timestamp: bigint;
    executed: boolean;
    cancelled: boolean;
  };
}

export interface StopLossOrderBookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "authorizeExecutor"
      | "authorizedExecutors"
      | "batchExecuteStopLoss"
      | "canExecute"
      | "cancelStopLossOrder"
      | "createStopLossOrder"
      | "emergencyWithdraw"
      | "executeStopLossOrder"
      | "executeStopLossOrderInternal"
      | "executorReward"
      | "feeRecipient"
      | "getExecutableOrders"
      | "getOrder"
      | "getTraderOrders"
      | "nextOrderId"
      | "orders"
      | "owner"
      | "platformFee"
      | "renounceOwnership"
      | "revokeExecutor"
      | "setExecutorReward"
      | "setFeeRecipient"
      | "setPlatformFee"
      | "tokenOrders"
      | "traderOrders"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "StopLossCancelled"
      | "StopLossCreated"
      | "StopLossExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedExecutors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchExecuteStopLoss",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canExecute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStopLossOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createStopLossOrder",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeStopLossOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeStopLossOrderInternal",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executorReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutableOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraderOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutorReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "traderOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchExecuteStopLoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelStopLossOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStopLossOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeStopLossOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeStopLossOrderInternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executorReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutableOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTraderOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutorReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "traderOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StopLossCancelledEvent {
  export type InputTuple = [orderId: BigNumberish, trader: AddressLike];
  export type OutputTuple = [orderId: bigint, trader: string];
  export interface OutputObject {
    orderId: bigint;
    trader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StopLossCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    trader: AddressLike,
    tokenAddress: AddressLike,
    triggerPrice: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    trader: string,
    tokenAddress: string,
    triggerPrice: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    trader: string;
    tokenAddress: string;
    triggerPrice: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StopLossExecutedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    executor: AddressLike,
    amountReceived: BigNumberish,
    executorRewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    executor: string,
    amountReceived: bigint,
    executorRewardAmount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    executor: string;
    amountReceived: bigint;
    executorRewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StopLossOrderBook extends BaseContract {
  connect(runner?: ContractRunner | null): StopLossOrderBook;
  waitForDeployment(): Promise<this>;

  interface: StopLossOrderBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  authorizeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedExecutors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchExecuteStopLoss: TypedContractMethod<
    [orderIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  canExecute: TypedContractMethod<[orderId: BigNumberish], [boolean], "view">;

  cancelStopLossOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createStopLossOrder: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      ammAddress: AddressLike,
      triggerPrice: BigNumberish,
      amount: BigNumberish,
      minReceive: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeStopLossOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeStopLossOrderInternal: TypedContractMethod<
    [orderId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;

  executorReward: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getExecutableOrders: TypedContractMethod<
    [tokenAddress: AddressLike],
    [bigint[]],
    "view"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [StopLossOrderBook.StopLossOrderStructOutput],
    "view"
  >;

  getTraderOrders: TypedContractMethod<
    [trader: AddressLike],
    [bigint[]],
    "view"
  >;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        orderId: bigint;
        trader: string;
        tokenAddress: string;
        ammAddress: string;
        triggerPrice: bigint;
        amount: bigint;
        minReceive: bigint;
        timestamp: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  setExecutorReward: TypedContractMethod<
    [newReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  traderOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedExecutors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchExecuteStopLoss"
  ): TypedContractMethod<[orderIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<[orderId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelStopLossOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createStopLossOrder"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      ammAddress: AddressLike,
      triggerPrice: BigNumberish,
      amount: BigNumberish,
      minReceive: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeStopLossOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeStopLossOrderInternal"
  ): TypedContractMethod<
    [orderId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executorReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExecutableOrders"
  ): TypedContractMethod<[tokenAddress: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [StopLossOrderBook.StopLossOrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTraderOrders"
  ): TypedContractMethod<[trader: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        orderId: bigint;
        trader: string;
        tokenAddress: string;
        ammAddress: string;
        triggerPrice: bigint;
        amount: bigint;
        minReceive: bigint;
        timestamp: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExecutorReward"
  ): TypedContractMethod<[newReward: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "traderOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StopLossCancelled"
  ): TypedContractEvent<
    StopLossCancelledEvent.InputTuple,
    StopLossCancelledEvent.OutputTuple,
    StopLossCancelledEvent.OutputObject
  >;
  getEvent(
    key: "StopLossCreated"
  ): TypedContractEvent<
    StopLossCreatedEvent.InputTuple,
    StopLossCreatedEvent.OutputTuple,
    StopLossCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StopLossExecuted"
  ): TypedContractEvent<
    StopLossExecutedEvent.InputTuple,
    StopLossExecutedEvent.OutputTuple,
    StopLossExecutedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StopLossCancelled(uint256,address)": TypedContractEvent<
      StopLossCancelledEvent.InputTuple,
      StopLossCancelledEvent.OutputTuple,
      StopLossCancelledEvent.OutputObject
    >;
    StopLossCancelled: TypedContractEvent<
      StopLossCancelledEvent.InputTuple,
      StopLossCancelledEvent.OutputTuple,
      StopLossCancelledEvent.OutputObject
    >;

    "StopLossCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      StopLossCreatedEvent.InputTuple,
      StopLossCreatedEvent.OutputTuple,
      StopLossCreatedEvent.OutputObject
    >;
    StopLossCreated: TypedContractEvent<
      StopLossCreatedEvent.InputTuple,
      StopLossCreatedEvent.OutputTuple,
      StopLossCreatedEvent.OutputObject
    >;

    "StopLossExecuted(uint256,address,uint256,uint256)": TypedContractEvent<
      StopLossExecutedEvent.InputTuple,
      StopLossExecutedEvent.OutputTuple,
      StopLossExecutedEvent.OutputObject
    >;
    StopLossExecuted: TypedContractEvent<
      StopLossExecutedEvent.InputTuple,
      StopLossExecutedEvent.OutputTuple,
      StopLossExecutedEvent.OutputObject
    >;
  };
}
